# Generated by Django 6.0 on 2025-12-09 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('PENDING_APPROVAL', 'Pending Approval'), ('AVAILABLE', 'Available'), ('SOLD', 'Sold')], default='AVAILABLE', max_length=20),
        ),
    ]
